POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5fZG9lMTIzIiwiaWQiOiI2NmU3MTQzNTU0Nzg1YWRmN2U4MjQyMDgiLCJpYXQiOjE3MjY0MjAwMzQsImV4cCI6MTcyNjQyMzYzNH0.A_s2yKXwNf8mas1MV3_3Rbrciclv1_bcf1GgX_UMGzg

{
    "title": "johns blog",
    "author": "ASD",
    "url": "http://haha.com/lmao",
    "likes": 1
}